from vishnu667/alpinebase:latest

MAINTAINER Vishnu Prasad <vishnu667@gmail.com>

RUN apk add --update ruby libffi-dev ruby-dev ruby-io-console zlib-dev ruby-irb  ruby-rdoc

Run rm -rf /var/cache/apk/*
WORKDIR /root
